import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, test, vi } from "vitest";
import * as native from "../src/native";
import { GradeImportReview } from "../src/features/study/GradeImportReview";
import type { StudyViewModel } from "../src/features/study/studyModel";
const draft:native.GradeImportPreview={id:"draft",courseId:"course",fileName:"grades.csv",revision:1,baseline:"baseline",headers:["Assignment","Score","Possible"],records:[["Quiz","0","10"]],studentRow:null,layout:"assignment_rows",mapping:{title:0,score:1,possible:2,category:null},sourceImage:null,warnings:[],rows:[{id:"row",title:"Quiz",score:0,pointsPossible:10,categoryId:null,status:"graded",selected:true,action:"add",replaceId:null,sourceId:null,evidence:"Quiz,0,10",locator:"CSV row 2",confidence:1,warnings:[]}]};
afterEach(()=>vi.restoreAllMocks());
test("grade review keeps corrected blanks and sources after failed explicit application",async()=>{
 const user=userEvent.setup();const apply=vi.spyOn(native,"applyGradeImport").mockRejectedValue(new Error("stale gradebook"));
 vi.spyOn(native,"listGradeImports").mockResolvedValue([structuredClone(draft)]);
 const save=vi.spyOn(native,"saveGradeImportReview").mockImplementation(async p=>({...p,revision:p.revision+1}));
 const vm={gradeCourse:"course",courses:[{id:"course",title:"Course"}],categories:[],busy:false,setBusy:vi.fn(),study:{gradeItems:[]},act:async(action:()=>Promise<unknown>)=>{try{await action();return true;}catch{return false;}}} as unknown as StudyViewModel;
 render(<GradeImportReview vm={vm}/>);
 await user.click(screen.getByText("Import grades for review",{selector:"summary"}));
 await waitFor(()=>expect(screen.getByLabelText("Reopen a saved import")).toBeVisible());
 await user.selectOptions(screen.getByLabelText("Reopen a saved import"),"draft");
 expect(screen.getByLabelText("Earned points")).toHaveValue(0);
 await user.clear(screen.getByLabelText("Earned points"));
 expect(apply).not.toHaveBeenCalled();
 await user.click(screen.getByRole("button",{name:"Apply 1 selected grade"}));
 expect(apply).toHaveBeenCalledWith("draft",2);
 expect(save.mock.calls[0][0].rows[0].score).toBeNull();
 expect(screen.getByLabelText("Earned points")).toHaveValue(null);
 await user.click(screen.getByText("Source evidence · 100% extraction confidence"));
 expect(screen.getByText("Quiz,0,10")).toBeVisible();
 await user.click(screen.getByRole("button",{name:"Apply 1 selected grade"}));
 expect(apply).toHaveBeenLastCalledWith("draft",3);
});
