import { useState } from "react";
import { saveGradeCategory, saveGradeItem, type GradeCategory, type GradeItem, type StudyWorkspace } from "../../native";
export function GradeItemEditor({item,busy,onSave}:{item:GradeItem;busy:boolean;onSave:(work:()=>Promise<StudyWorkspace>)=>void}){
 const [draft,setDraft]=useState(item),[editing,setEditing]=useState(false);
 if(!editing)return <button className="text-button" onClick={()=>{setDraft(item);setEditing(true);}}>Edit {item.title}</button>;
 return <form aria-label={`Edit grade ${item.title}`} onSubmit={e=>{e.preventDefault();onSave(async()=>{const saved=await saveGradeItem({...draft,categoryId:draft.categoryId??undefined,dueAt:draft.dueAt??undefined,score:draft.score??undefined});setEditing(false);return saved;});}}>
 <label className="field">Grade title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field">Grade score<input type="number" min="0" value={draft.score??""} onChange={e=>setDraft({...draft,score:e.target.value===""?undefined:Number(e.target.value)})}/></label><label className="field">Grade points possible<input type="number" min="0.1" step="any" value={draft.pointsPossible} onChange={e=>setDraft({...draft,pointsPossible:Number(e.target.value)})}/></label><label className="field">Grade status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as GradeItem["status"]})}><option value="graded">Graded</option><option value="missing">Missing</option><option value="planned">What-if / planned</option></select></label><button className="solid" disabled={busy||!draft.title.trim()||draft.pointsPossible<=0}>Save grade edits</button><button type="button" className="text-button" onClick={()=>setEditing(false)}>Cancel grade edit</button>
 </form>;
}
export function GradeCategoryEditor({item,busy,onSave}:{item:GradeCategory;busy:boolean;onSave:(work:()=>Promise<StudyWorkspace>)=>void}){
 const [draft,setDraft]=useState(item),[editing,setEditing]=useState(false);
 return editing?<form aria-label={`Edit category ${item.name}`} onSubmit={e=>{e.preventDefault();onSave(async()=>{const saved=await saveGradeCategory(draft);setEditing(false);return saved;});}}><label className="field">Category name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field">Category weight<input type="number" min="0" max="100" value={draft.weight} onChange={e=>setDraft({...draft,weight:Number(e.target.value)})}/></label><button className="outline" disabled={busy||!draft.name.trim()}>Save category edits</button><button type="button" className="text-button" onClick={()=>setEditing(false)}>Cancel category edit</button></form>:<button className="text-button" onClick={()=>{setDraft(item);setEditing(true);}}>Edit {item.name}</button>;
}
