import { useEffect, useState } from "react";
import { applyGradeImport, discardGradeImport, listGradeImports, previewGradeImport, refreshGradeImport, retryGradeImport, saveGradeImportReview, type GradeImportPreview, type GradeImportRow } from "../../native";
import type { StudyViewModel } from "./studyModel";

export function GradeImportReview({ vm }: { vm:StudyViewModel }) {
  const [draft,setDraft]=useState<GradeImportPreview|null>(null);
  const [saved,setSaved]=useState<GradeImportPreview[]>([]);
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>{let active=true;setDraft(null);setError("");setNotice("");void listGradeImports(vm.gradeCourse).then(values=>{if(active)setSaved(values);}).catch(()=>{if(active)setError("Saved import drafts could not be loaded. Reopen Grades to retry.");});return()=>{active=false;};},[vm.gradeCourse]);
  const work=async(action:()=>Promise<void>)=>{setBusy(true);vm.setBusy(true);setError("");try{await action();}catch(e){setError(String(e));}finally{setBusy(false);vm.setBusy(false);}};
  const change=(id:string,patch:Partial<GradeImportRow>)=>setDraft(p=>p?{...p,rows:p.rows.map(r=>r.id===id?{...r,...patch}:r)}:p);
  const save=async()=>{if(!draft)return;const next=await saveGradeImportReview(draft);setDraft(next);setSaved(await listGradeImports(vm.gradeCourse));setNotice("Review draft saved locally. No grades were applied.");};
  const reparse=async()=>{if(draft){setDraft(await saveGradeImportReview(draft,true));setSaved(await listGradeImports(vm.gradeCourse));setNotice("Rows extracted using your mapping. Review before applying.");}};
  const selected=draft?.rows.filter(r=>r.selected&&r.action!=="skip")??[];
  const invalid=selected.some(r=>!r.title.trim()||r.pointsPossible===null||r.pointsPossible<=0||r.score!==null&&r.score<0||r.action==="replace"&&!r.replaceId);
  return <details className="progressive-form grade-import"><summary>Import grades for review</summary>
    <p>Canvas CSV or gradebook PNG/JPEG. Read locally; select and correct rows before applying. Weights and dropped-score rules are never imported.</p>
    <label className="field">Choose gradebook file<input type="file" accept=".csv,.png,.jpg,.jpeg,text/csv,image/png,image/jpeg" disabled={busy||vm.busy} onChange={e=>{const file=e.target.files?.[0];e.target.value="";if(file)void work(async()=>{const p=await previewGradeImport(vm.gradeCourse,file);setDraft(p);setSaved(await listGradeImports(vm.gradeCourse));});}}/></label>
    {saved.length>0&&<label className="field">Reopen a saved import<select value={draft?.id??""} disabled={busy} onChange={e=>setDraft(saved.find(p=>p.id===e.target.value)??null)}><option value="">Choose a draft</option>{saved.map(p=><option key={p.id} value={p.id}>{p.fileName}</option>)}</select></label>}
    {error&&<p role="alert" className="error-summary">{error} Your review remains editable.</p>}{notice&&<p role="status">{notice}</p>}
    {draft&&<div aria-label="Grade import review"><h3>Review {draft.fileName}</h3><p>Course: {vm.courses.find(c=>c.id===draft.courseId)?.title}. Blank earned points stay blank.</p>
      {draft.warnings.length>0&&<ul>{draft.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul>}
      {draft.sourceImage&&<details><summary>Original gradebook image</summary><img className="grade-source-image" src={draft.sourceImage} alt="Original gradebook source for reviewing extracted rows"/></details>}
      {draft.layout==="canvas_columns"?<label className="field">Student row<select disabled={busy} value={draft.studentRow??""} onChange={e=>setDraft({...draft,studentRow:e.target.value===""?null:Number(e.target.value)})}><option value="">Choose yourself explicitly</option>{draft.records.map((r,i)=>r[0]?.trim().toLowerCase()!=="points possible"&&<option key={i} value={i}>CSV row {i+2}: {r.slice(0,4).join(" · ")}</option>)}</select></label>:draft.layout!=="image"&&<fieldset><legend>CSV column mapping</legend><div className="form-grid">{(["title","score","possible","category"] as const).map(key=><label className="field" key={key}>{({title:"Assignment column",score:"Earned-points column",possible:"Possible-points column",category:"Category column"})[key]}<select value={draft.mapping?.[key]??""} disabled={busy} onChange={e=>setDraft({...draft,mapping:{...(draft.mapping??{title:0,score:null,possible:null,category:null}),[key]:e.target.value===""?null:Number(e.target.value)}})}>{key!=="title"&&<option value="">Not reported</option>}{draft.headers.map((h,i)=><option key={i} value={i}>{h||`Column ${i+1}`}</option>)}</select></label>)}</div></fieldset>}
      {draft.layout!=="image"&&<button className="outline" disabled={busy||draft.layout==="canvas_columns"&&draft.studentRow===null} onClick={()=>void work(reparse)}>Extract rows using this selection</button>}
      {draft.layout==="image"&&!draft.rows.length&&<button className="outline" disabled={busy} onClick={()=>void work(async()=>{const next=await retryGradeImport(draft.id,draft.revision);setDraft(next);setSaved(await listGradeImports(vm.gradeCourse));setNotice("Local OCR retried. Review extracted rows before applying.");})}>Retry local grade OCR</button>}
      {!draft.rows.length&&<p>No extracted rows yet. Check the selected student or columns, or import a clearer source.</p>}
      <div className="grade-import-rows">{draft.rows.map((r,i)=><fieldset key={r.id} disabled={busy}><legend>Row {i+1}: {r.title}</legend>
        <label className="confirm-row"><input type="checkbox" checked={r.selected} disabled={busy} onChange={e=>change(r.id,{selected:e.target.checked,action:e.target.checked&&r.action==="skip"?"add":r.action})}/>I reviewed this row; include it</label>
        <div className="form-grid"><label className="field">Assignment<input value={r.title} maxLength={200} onChange={e=>change(r.id,{title:e.target.value})}/></label><label className="field">Earned points<input type="number" min="0" step="any" value={r.score??""} onChange={e=>change(r.id,{score:e.target.value===""?null:Number(e.target.value)})}/></label><label className="field">Possible points<input type="number" min="0.01" step="any" value={r.pointsPossible??""} onChange={e=>change(r.id,{pointsPossible:e.target.value===""?null:Number(e.target.value)})}/></label>
        <label className="field">Category<select value={r.categoryId??""} onChange={e=>change(r.id,{categoryId:e.target.value||null})}><option value="">Uncategorized</option>{vm.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
        <label className="field">Status<select value={r.status} onChange={e=>change(r.id,{status:e.target.value as GradeImportRow["status"]})}><option value="graded">Graded / score not reported</option><option value="missing">Missing — confirmed by me</option></select></label>
        <label className="field">Apply as<select value={r.action} onChange={e=>change(r.id,{action:e.target.value as GradeImportRow["action"]})}><option value="skip">Skip</option><option value="add">Add new grade</option><option value="replace">Replace an existing grade</option></select></label>
        {r.action==="replace"&&<label className="field">Grade to replace<select value={r.replaceId??""} onChange={e=>change(r.id,{replaceId:e.target.value||null})}><option value="">Choose existing grade</option>{vm.study?.gradeItems.filter(g=>g.courseId===draft.courseId).map(g=><option key={g.id} value={g.id}>{g.title} · {g.score??"—"}/{g.pointsPossible}</option>)}</select></label>}</div>
        <details><summary>Source evidence · {Math.round(r.confidence*100)}% extraction confidence</summary><small>{r.locator}</small><blockquote>{r.evidence}</blockquote>{r.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>
      </fieldset>)}</div>
      <div className="record-actions"><button className="outline" disabled={busy} onClick={()=>void work(save)}>Save review draft</button><button className="outline" disabled={busy} onClick={()=>void work(async()=>{await save();const current=await refreshGradeImport(draft.id);setDraft(current);setSaved(await listGradeImports(vm.gradeCourse));setNotice("Updated against the current gradebook. Select reviewed rows again.");})}>Refresh duplicate checks</button>
        <button className="solid" disabled={busy||vm.busy||!selected.length||invalid} onClick={()=>void work(async()=>{const next=await saveGradeImportReview(draft);setDraft(next);const ok=await vm.act(()=>applyGradeImport(next.id,next.revision),"Reviewed grades applied locally.");if(ok){setDraft(null);setSaved(await listGradeImports(vm.gradeCourse));}})}>Apply {selected.length} selected grade{selected.length===1?"":"s"}</button>
        <button className="text-button" disabled={busy} onClick={()=>void work(async()=>{await discardGradeImport(draft.id);setDraft(null);setSaved(await listGradeImports(vm.gradeCourse));})}>Discard this import</button></div>
    </div>}
  </details>;
}
