import { useEffect, useRef, useState } from "react";
import { deleteStudyNote, getStudySourceText, importStudySource, saveStudyNote, type StudyArtifact, type StudyNoteInput, type StudySourceText } from "../../native";
import type { StudyViewModel } from "./studyModel";
import "../student/student.css";
const templates = {
 notes:"# Key ideas\n\n# Details\n\n# Questions\n\n# Action items\n",
 summary:"# Summary\n\n# Main points\n\n# Open questions\n",
 outline:"# Topic\n\n## Main idea\n- Evidence\n- Examples\n\n## Next steps\n",
 slides:"# Slide 1: Title\n- Main idea\n\nSpeaker notes:\n\n# Slide 2: Key points\n- Point\n- Evidence\n\nSpeaker notes:\n\n# Slide 3: Takeaways\n- Takeaway\n\nSpeaker notes:\n",
};
export function SourceViewer({documentId,onClose}:{documentId:string;onClose:()=>void}){
 const [source,setSource]=useState<StudySourceText[]|null>(null),[error,setError]=useState("");
 // Mount keyed by source ID; fetching does not send data to an AI provider.
 useEffect(()=>{let active=true;getStudySourceText(documentId).then(s=>{if(active)setSource(s);}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[documentId]);
 return <section className="workspace-panel" aria-label="Source text"><div className="section-head"><h3>Source text</h3><button className="outline" onClick={onClose}>Close source</button></div>{error?<p role="alert">{error}</p>:source?source.map(s=><article key={s.id}><strong>{s.locator}</strong><p className="source-text">{s.text}</p></article>):<p aria-busy="true">Opening local source…</p>}</section>;
}
export function NotesOrganizer({vm}:{vm:StudyViewModel}){
 const {courses,study,busy,act,setStudy,setError,setNotice}=vm;
 const editorTrigger=useRef<HTMLElement|null>(null);
 const first=vm.selectedCourses[0]??courses[0]?.id??"";
 const empty=():StudyNoteInput=>({expectedRevision:0,courseId:first,kind:"notes",title:"",content:"",tags:[],pinned:false,sourceIds:[]});
 const [draft,setDraft]=useState<StudyNoteInput|null>(null),[tagsText,setTagsText]=useState(""),[query,setQuery]=useState(""),[course,setCourse]=useState(first),[group,setGroup]=useState("date"),[tag,setTag]=useState(""),[pasted,setPasted]=useState(""),[sourceId,setSourceId]=useState<string|null>(null),[deleting,setDeleting]=useState<StudyArtifact|null>(null),[importing,setImporting]=useState(false);
 const notes=(study?.artifacts??[]).filter(n=>(!course||n.courseId===course)&&`${n.title} ${n.content} ${(n.tags??[]).join(" ")}`.toLowerCase().includes(query.toLowerCase())&&(!tag||(n.tags??[]).includes(tag))).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updatedAt.localeCompare(a.updatedAt));
 const grouped=new Map<string,StudyArtifact[]>();for(const note of notes){const key=group==="topic"?(note.tags?.[0]??"Untagged"):group==="course"?(courses.find(c=>c.id===note.courseId)?.code??"Course"):new Date(note.updatedAt).toLocaleDateString(undefined,{timeZone:vm.timezone});grouped.set(key,[...(grouped.get(key)??[]),note]);}
 const closeEditor=()=>{setDraft(null);editorTrigger.current?.focus();};
 const edit=(n:StudyArtifact,trigger:HTMLElement)=>{editorTrigger.current=trigger;setTagsText((n.tags??[]).join(", "));setDraft({id:n.id,expectedRevision:n.revision??1,courseId:n.courseId,kind:n.kind,title:n.title,content:n.content,tags:n.tags??[],pinned:n.pinned??false,sourceIds:n.sourceIds??[]});};
 const importFile=async(file:File)=>{setImporting(true);setError("");try{setStudy(await importStudySource(course,file));setPasted("");setNotice("Source imported into Materials. Review its extraction status.");}catch(e){setError(String(e));}finally{setImporting(false);}};
 return <section className="notes-organizer" aria-label="Organized course notes"><div className="section-head"><div><h2>Notes workspace</h2><p>Write locally, organize study artifacts, or draft from the sources already in Materials.</p></div><button className="solid" disabled={!courses.length} onClick={e=>{editorTrigger.current=e.currentTarget;setTagsText("");setDraft({...empty(),courseId:course||first});}}>Write a note</button></div>
  <div className="form-grid"><label className="field">Search notes<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Title, content, or tag"/></label><label className="field">Notes course<select value={course} onChange={e=>setCourse(e.target.value)}><option value="">All courses</option>{courses.map(c=><option value={c.id} key={c.id}>{c.code||c.title}</option>)}</select></label><label className="field">Group notes by<select value={group} onChange={e=>setGroup(e.target.value)}><option value="date">Date updated</option><option value="topic">First topic / tag</option><option value="course">Course</option></select></label><label className="field">Filter note tag<select value={tag} onChange={e=>setTag(e.target.value)}><option value="">All tags</option>{[...new Set(study?.artifacts.flatMap(n=>n.tags??[])??[])].sort().map(t=><option value={t} key={t}>{t}</option>)}</select></label></div>
  <details><summary>Import a source or text transcript</summary><p>Choose a course above. PDF, DOCX, PPTX, TXT, PNG, JPEG, and TIFF use local extraction. Images and scanned PDFs require available OCR. Audio transcription and slide export are unavailable.</p><label className="field">Import material file<input type="file" accept=".pdf,.docx,.pptx,.txt,.png,.jpg,.jpeg,.tif,.tiff" disabled={importing||!course} onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.target.value="";}}/></label><label className="field">Paste text or meeting transcript<textarea value={pasted} maxLength={100000} onChange={e=>setPasted(e.target.value)}/></label><button className="outline" disabled={importing||!pasted.trim()||!course} onClick={()=>void importFile(new File([pasted],"meeting-transcript.txt",{type:"text/plain"}))}>{importing?"Importing…":"Save text as source"}</button></details>
  {draft&&<form onSubmit={e=>{e.preventDefault();void act(async()=>{const next=await saveStudyNote({...draft,tags:tagsText.split(",").map(t=>t.trim()).filter(Boolean)});closeEditor();return next;},"Note saved locally.");}} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){e.preventDefault();e.currentTarget.requestSubmit();}}}>
    <div className="section-head"><h3>{draft.id?"Edit note":"New note"}</h3><button className="text-button" type="button" onClick={closeEditor}>Close editor</button></div><div className="form-grid"><label className="field">Note title<input autoFocus maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field">Note course<select disabled={Boolean(draft.id)} value={draft.courseId} onChange={e=>setDraft({...draft,courseId:e.target.value,sourceIds:[]})}>{courses.map(c=><option key={c.id} value={c.id}>{c.code||c.title}</option>)}</select></label><label className="field">Note format<select disabled={Boolean(draft.id)} value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}>{Object.keys(templates).map(k=><option value={k} key={k}>{k==="slides"?"Slide draft":k}</option>)}{!Object.keys(templates).includes(draft.kind)&&<option value={draft.kind}>{draft.kind.replaceAll("_"," ")}</option>}</select></label><label className="field">Note tags<input value={tagsText} onChange={e=>setTagsText(e.target.value)}/></label></div>
    <label className="field">Note content<textarea rows={12} maxLength={40000} value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><label><input type="checkbox" checked={draft.pinned} onChange={e=>setDraft({...draft,pinned:e.target.checked})}/> Pin this note</label>
    {!draft.id&&<fieldset><legend>Link existing source materials</legend>{study?.materials.filter(m=>m.courseIds.includes(draft.courseId)).map(m=><label key={m.id}><input type="checkbox" checked={draft.sourceIds.includes(m.id)} onChange={e=>setDraft({...draft,sourceIds:e.target.checked?[...draft.sourceIds,m.id]:draft.sourceIds.filter(id=>id!==m.id)})}/>{m.title}</label>)}</fieldset>}
    <div className="record-actions"><button className="solid" disabled={busy||!draft.title.trim()||!draft.content.trim()}>Save note</button><button type="button" className="outline" disabled={Boolean(draft.content.trim())} onClick={()=>setDraft({...draft,content:templates[draft.kind as keyof typeof templates]??templates.notes})}>Insert manual template</button></div>
  </form>}
  {!notes.length&&<p>{study?.artifacts.length?"No notes match these filters.":"No organized notes yet. Write one locally or create a reviewed draft from your materials."}</p>}
  {[...grouped].map(([key,items])=><section key={key}><h3>{key}</h3>{items.map(n=><article className="quick-note" key={n.id}><div className="section-head"><div><strong>{n.title}</strong><small>{n.pinned?" · Pinned":""} · {n.kind.replaceAll("_"," ")} · {(n.tags??[]).join(", ")}</small></div><button className="outline" onClick={e=>edit(n,e.currentTarget)}>Edit organized note</button></div><p className="note-content">{n.content.slice(0,350)}{n.content.length>350?"…":""}</p><div className="record-actions">{(n.sourceIds??[]).map(id=><button className="text-button" key={id} onClick={()=>setSourceId(id)}>Open {study?.materials.find(m=>m.id===id)?.title??"source unavailable"}</button>)}<button className="text-button danger" onClick={()=>setDeleting(n)}>Delete organized note</button></div>{n.citations.length>0&&<details><summary>Cited references</summary>{n.citations.map((c,i)=><p key={i}>{c.locator} · “{c.quote}”</p>)}</details>}{deleting?.id===n.id&&<div><p>Delete this note? Source materials remain in the vault.</p><button className="outline danger" disabled={busy} onClick={()=>void act(async()=>{const next=await deleteStudyNote(n.id,n.revision??1);setDeleting(null);return next;},"Note deleted.")}>Confirm note deletion</button><button className="text-button" onClick={()=>setDeleting(null)}>Keep note</button></div>}</article>)}</section>)}
  {sourceId&&<SourceViewer key={sourceId} documentId={sourceId} onClose={()=>setSourceId(null)}/>}
 </section>;
}
