import { useEffect, useState } from "react";
import type { Dashboard } from "../../native";
import { workflowApi, type WorkflowState, type CheckinItem } from "./workflowApi";
import "./student.css";
export function DailyReview({suppressed,onDashboard,onEditTask,onTaskCompleted}:{suppressed:boolean;onDashboard:(d:Dashboard)=>void;onEditTask:(id:string)=>void;onTaskCompleted?:(id:string,d:Dashboard)=>void}) {
  const [state,setState]=useState<WorkflowState|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[earlier,setEarlier]=useState<{item:CheckinItem;time:string}|null>(null);
  const load=async()=>{if(suppressed||document.hidden)return;try{setState(await workflowApi.state(true));setError("");}catch(e){setError(String(e));}};
  useEffect(()=>{void load();const tick=window.setInterval(()=>void load(),30_000);const foreground=()=>void load();window.addEventListener("focus",foreground);document.addEventListener("visibilitychange",foreground);return()=>{clearInterval(tick);window.removeEventListener("focus",foreground);document.removeEventListener("visibilitychange",foreground);};},[suppressed]);
  const action=async(work:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await work();await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
  const answer=async(item:CheckinItem,answer:string,at:string|null=null)=>{if(!state?.checkin||item.taskVersion==null)return;await action(async()=>{const next=await workflowApi.respond({day:state.checkin!.day,taskId:item.taskId,action:answer,expectedVersion:item.taskVersion!,completedAt:at});onDashboard(next);setEarlier(null);if(answer==="complete"&&!item.completed)onTaskCompleted?.(item.taskId,next);});};
  if(suppressed)return null;
  return <div className="student-daily-review">
    {error&&<p role="alert" className="error-summary">{error}<button onClick={()=>void load()}>Reload daily review</button></p>}
    {state&&!state.settings.enabled&&!state.settings.offerDismissed&&<section className="daily-checkin" aria-label="Enable daily check-in"><h2>A moment to finish your day</h2><p>Review planned and due tasks yourself. Coqui never assumes a deadline means work is done.</p><div className="record-actions"><button className="outline" disabled={busy} onClick={()=>void action(()=>workflowApi.settings({...state.settings,enabled:true,offerDismissed:true}))}>Enable daily check-in</button><button className="text-button" onClick={()=>void action(()=>workflowApi.settings({...state.settings,offerDismissed:true}))}>Dismiss</button></div><small>Starts at 8 PM, or follows your saved daily rhythm. Change it in Notifications.</small></section>}
    {state?.checkin&&<section className="daily-checkin" aria-label="Daily task check-in"><div className="section-head"><div><h2>How did your day go?</h2><p>Tasks planned or due on {state.checkin.day} · {state.checkin.timezone}</p></div></div><p>Confirm each task. Dates change only after you review and save them in Work.</p>
      {state.checkin.items.map(item=><article className="checkin-item" key={item.taskId}><strong>{item.title}</strong>{item.unavailable?<p>Task no longer available.</p>:item.completed?<p>Completed</p>:item.response?<p>{item.response.replaceAll("_"," ")}</p>:<div className="record-actions"><button className="solid" disabled={busy} onClick={()=>void answer(item,"complete")}>Complete now</button><button className="outline" disabled={busy} onClick={()=>setEarlier({item,time:""})}>Completed earlier</button><button className="outline" disabled={busy} onClick={()=>void answer(item,"in_progress")}>Still in progress</button><button className="outline" disabled={busy} onClick={()=>void answer(item,"not_completed")}>Not completed</button>{item.rescheduled&&<button className="outline" disabled={busy} onClick={()=>void answer(item,"rescheduled")}>Confirm saved reschedule</button>}<button className="text-button" onClick={()=>onEditTask(item.taskId)}>Review / reschedule</button></div>}</article>)}
      {earlier&&<div role="group" aria-label="Confirm earlier completion"><label className="field">Actual completion time (include timezone offset)<input value={earlier.time} onChange={e=>setEarlier({...earlier,time:e.target.value})} placeholder="2026-09-29T18:00:00-07:00"/></label><p>You are confirming when you actually finished “{earlier.item.title}”. Coqui keeps the time of this confirmation separately.</p><button className="solid" disabled={busy||!/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(earlier.time)||!Number.isFinite(Date.parse(earlier.time))} onClick={()=>void answer(earlier.item,"complete",earlier.time)}>Confirm completion time</button><button className="text-button" onClick={()=>setEarlier(null)}>Cancel</button></div>}
      <div className="record-actions"><button className="outline" disabled={busy} onClick={()=>void action(()=>workflowApi.control(state.checkin!.day,"snooze"))}>Snooze 30 minutes</button><button className="text-button" disabled={busy} onClick={()=>void action(()=>workflowApi.control(state.checkin!.day,"dismiss"))}>Dismiss this day</button><button className="text-button" disabled={busy} onClick={()=>void action(()=>workflowApi.settings({...state.settings,enabled:false,offerDismissed:true}))}>Turn check-ins off</button></div>
    </section>}
    {state?.settings.streakVisible&&state.streak.entries.length>0&&<section className="assignment-streak" aria-label="On-time assignment streak"><div className="section-head"><h2>{state.streak.count} on-time assignment{state.streak.count===1?"":"s"} in a row</h2><button className="text-button" onClick={()=>void action(()=>workflowApi.settings({...state.settings,streakVisible:false}))}>Hide streak</button></div><details><summary>Which assignments count?</summary><p>Assignments and assessments with deadlines count in due-time order. Completion at the deadline counts. Late or unfinished past-due work starts a new sequence; future work waits. Reading, study sessions, and undated tasks do not count.</p><p>The scoring deadline freezes when you complete the assignment or its deadline arrives. Later rescheduling changes planning, and keeps that deadline visible here.</p><ul>{state.streak.entries.map(e=><li key={e.taskId}><strong>{e.title}</strong> · {e.outcome.replaceAll("_"," ")} · scoring deadline {new Date(e.dueAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}{e.completedAt?` · completed ${new Date(e.completedAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}`:""}{e.legacy?" · earlier deadline history unavailable":""}{e.currentDueAt&&e.currentDueAt!==e.dueAt?` · planning deadline ${new Date(e.currentDueAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}`:""}{e.deleted?" · deleted task, history retained":""}{Boolean(e.history?.length)&&<details><summary>Completion and correction history</summary><ul>{e.history?.map((h,i)=><li key={i}>{h.kind.replaceAll("_"," ")} · entered {new Date(h.recordedAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}{h.completedAt?` · asserted completion ${new Date(h.completedAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}`:""}{h.dueAt?` · edited deadline ${new Date(h.dueAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}`:""}</li>)}</ul></details>}</li>)}</ul></details></section>}
  </div>;
}
