import { useEffect, useRef, useState } from "react";
import type { Dashboard } from "../../native";
import { workflowApi, type WorkflowState, type CheckinItem } from "./workflowApi";
import "./student.css";
import { completionInstants, timezoneLabel } from "./completionTime";
export function DailyReview({suppressed,onDashboard,onEditTask,onTaskCompleted}:{suppressed:boolean;onDashboard:(d:Dashboard)=>void;onEditTask:(id:string)=>void;onTaskCompleted?:(id:string,d:Dashboard)=>void}) {
  const [state,setState]=useState<WorkflowState|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[earlier,setEarlier]=useState<{item:CheckinItem;date:string;time:string;instant:string}|null>(null);
  const [notice,setNotice]=useState("");
  const root=useRef<HTMLDivElement>(null);
  const [focusAfter,setFocusAfter]=useState<string|null>(null);
  useEffect(()=>{if(focusAfter===null||busy)return; const buttons=Array.from(root.current?.querySelectorAll<HTMLButtonElement>("button[data-checkin-primary]")??[]); const current=state?.checkin?.items.findIndex(i=>i.taskId===focusAfter)??-1; const items=state?.checkin?.items??[];const next=[...items.slice(current+1),...items.slice(0,current)].find(i=>!i.completed&&!i.response&&!i.unavailable); (buttons.find(b=>b.dataset.checkinPrimary===next?.taskId)??root.current?.querySelector<HTMLElement>("#daily-checkin-heading"))?.focus();setFocusAfter(null);},[state,busy,focusAfter]);
  const load=async(clearError=false)=>{if(suppressed||document.hidden)return;try{setState(await workflowApi.state(true));if(clearError)setError("");}catch(e){setError(String(e));}};
  useEffect(()=>{void load();const tick=window.setInterval(()=>void load(),30_000);const foreground=()=>void load();window.addEventListener("focus",foreground);document.addEventListener("visibilitychange",foreground);return()=>{clearInterval(tick);window.removeEventListener("focus",foreground);document.removeEventListener("visibilitychange",foreground);};},[suppressed]);
  const action=async(work:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await work();await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
  const answer=async(item:CheckinItem,answer:string,at:string|null=null)=>{if(!state?.checkin||item.taskVersion==null)return;await action(async()=>{const next=await workflowApi.respond({day:state.checkin!.day,taskId:item.taskId,action:answer,expectedVersion:item.taskVersion!,completedAt:at});onDashboard(next);setEarlier(null);setNotice(`Saved: ${item.title}.`);setFocusAfter(item.taskId);if(answer==="complete"&&!item.completed)onTaskCompleted?.(item.taskId,next);});};
  if(suppressed)return null;
  return <div className="student-daily-review" ref={root}>
    {notice&&<p role="status" className="workflow-status">{notice}</p>}
    {error&&<p role="alert" className="error-summary">{error}<button onClick={()=>void load(true)}>Reload daily review</button></p>}
    {state&&!state.settings.enabled&&!state.settings.offerDismissed&&<section className="daily-checkin" aria-label="Enable daily check-in"><h2>A moment to finish your day</h2><p>Review planned and due tasks yourself. Coqui never assumes a deadline means work is done.</p><div className="record-actions"><button className="outline" disabled={busy} onClick={()=>void action(()=>workflowApi.settings({...state.settings,enabled:true,offerDismissed:true}))}>Enable daily check-in</button><button className="text-button" onClick={()=>void action(()=>workflowApi.settings({...state.settings,offerDismissed:true}))}>Dismiss</button></div><small>Starts at 8 PM, or follows your saved daily rhythm. Change it in Notifications.</small></section>}
    {state?.checkin&&<section className="daily-checkin" aria-label="Daily task check-in"><div className="section-head"><div><h2 id="daily-checkin-heading" tabIndex={-1}>How did your day go?</h2><p>Tasks planned or due on {new Date(`${state.checkin.day}T12:00:00`).toLocaleDateString()} · {timezoneLabel(state.checkin.timezone)}</p></div></div><p>Confirm each task. Dates change only after you review and save them in Work.</p>
      {state.checkin.items.map(item=><article className="checkin-item" key={item.taskId} aria-label={item.title}>
        <div className="checkin-row"><strong>{item.title}</strong>{item.unavailable?<span>Task no longer available.</span>:item.completed?<span>Completed</span>:item.response?<span>{item.response.replaceAll("_"," ")}</span>:<div className="record-actions">
          <button className="solid" data-checkin-primary={item.taskId} disabled={busy} onClick={()=>void answer(item,"complete")}>Complete now</button>
          <details><summary>More options</summary><div className="checkin-options"><button className="text-button" disabled={busy} onClick={()=>setEarlier({item,date:state.checkin!.day,time:"",instant:""})}>Completed earlier</button><button className="text-button" disabled={busy} onClick={()=>void answer(item,"in_progress")}>Still in progress</button><button className="text-button" disabled={busy} onClick={()=>void answer(item,"not_completed")}>Not completed</button>{item.rescheduled&&<button className="text-button" disabled={busy} onClick={()=>void answer(item,"rescheduled")}>Confirm saved reschedule</button>}</div></details>
          <button className="text-button" disabled={busy} onClick={()=>onEditTask(item.taskId)}>Review / reschedule</button>
        </div>}</div>
        {earlier?.item.taskId===item.taskId&&(()=>{const instants=completionInstants(earlier.date,earlier.time,state.checkin!.timezone); const chosen=instants.length===1?instants[0]:earlier.instant;return <div role="group" aria-label="Confirm earlier completion" className="checkin-earlier">
          <div className="form-grid"><label className="field">Completion date<input autoFocus disabled={busy} type="date" value={earlier.date} onChange={e=>setEarlier({...earlier,date:e.target.value,instant:""})}/></label><label className="field">Completion time<input type="time" disabled={busy} value={earlier.time} onChange={e=>setEarlier({...earlier,time:e.target.value,instant:""})}/></label></div>
          <small>{timezoneLabel(state.checkin!.timezone,chosen?new Date(chosen):new Date())}. The confirmation time is recorded separately.</small>
          {earlier.time&&instants.length===0&&<p role="alert">This local time does not exist or is invalid. Choose another time.</p>}
          {instants.length>1&&<label className="field">This time occurs twice. Which one?<select disabled={busy} value={earlier.instant} onChange={e=>setEarlier({...earlier,instant:e.target.value})}><option value="">Choose an occurrence</option>{instants.map(at=><option key={at} value={at}>{new Date(at).toLocaleTimeString(undefined,{timeZone:state.checkin!.timezone,timeZoneName:"shortOffset"})}</option>)}</select></label>}
          <div className="record-actions"><button className="solid" disabled={busy||!chosen||!instants.includes(chosen)} onClick={()=>void answer(item,"complete",chosen)}>Confirm completion time</button><button className="text-button" disabled={busy} onClick={()=>{setEarlier(null);Array.from(root.current?.querySelectorAll<HTMLButtonElement>("button[data-checkin-primary]")??[]).find(b=>b.dataset.checkinPrimary===item.taskId)?.focus();}}>Cancel</button></div>
        </div>;})()}
      </article>)}
      <div className="record-actions"><button className="outline" disabled={busy} onClick={()=>void action(()=>workflowApi.control(state.checkin!.day,"snooze"))}>Snooze 30 minutes</button><button className="text-button" disabled={busy} onClick={()=>void action(()=>workflowApi.control(state.checkin!.day,"dismiss"))}>Dismiss this day</button><button className="text-button" disabled={busy} onClick={()=>void action(()=>workflowApi.settings({...state.settings,enabled:false,offerDismissed:true}))}>Turn check-ins off</button></div>
    </section>}
    {state?.settings.streakVisible&&state.streak.entries.length>0&&<section className="assignment-streak" aria-label="On-time assignment streak"><div className="section-head"><strong>{state.streak.count} on-time assignment{state.streak.count===1?"":"s"} in a row</strong><button className="text-button" onClick={()=>void action(()=>workflowApi.settings({...state.settings,streakVisible:false}))}>Hide streak</button></div><details><summary>About this streak</summary><p>Assignments and assessments with deadlines count in due-time order. Completion at the deadline counts. Late or unfinished past-due work starts a new sequence; future work waits. Reading, study sessions, and undated tasks do not count.</p><p>The scoring deadline freezes when you complete the assignment or its deadline arrives. Later rescheduling changes planning, and keeps that deadline visible here.</p><ul>{state.streak.entries.map(e=><li key={e.taskId}><strong>{e.title}</strong> · {e.outcome.replaceAll("_"," ")} · scoring deadline {new Date(e.dueAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}{e.completedAt?` · completed ${new Date(e.completedAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}`:""}{e.legacy?" · earlier deadline history unavailable":""}{e.currentDueAt&&e.currentDueAt!==e.dueAt?` · planning deadline ${new Date(e.currentDueAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}`:""}{e.deleted?" · deleted task, history retained":""}{Boolean(e.history?.length)&&<details><summary>Completion and correction history</summary><ul>{e.history?.map((h,i)=><li key={i}>{h.kind.replaceAll("_"," ")} · entered {new Date(h.recordedAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}{h.completedAt?` · asserted completion ${new Date(h.completedAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}`:""}{h.dueAt?` · edited deadline ${new Date(h.dueAt).toLocaleString(undefined,{timeZone:state.timezone??"UTC"})}`:""}</li>)}</ul></details>}</li>)}</ul></details></section>}
  </div>;
}
