import { useEffect, useRef, useState } from "react";
import { Crop, ImagePlus, RotateCcw, RotateCw, WandSparkles } from "lucide-react";
import { Dashboard, importDocumentBytes } from "../native";

type Photo={id:string;file:File;preview:string;rotation:0|90|180|270;crop:number;perspective:number};

export function SchedulePhotoEditor({disabled,onImported,onError}:{disabled:boolean;onImported:(dashboard:Dashboard,count:number)=>void;onError:(message:string)=>void}){
  const [photos,setPhotos]=useState<Photo[]>([]);const [busy,setBusy]=useState(false);const photosRef=useRef(photos);photosRef.current=photos;
  useEffect(()=>()=>photosRef.current.forEach(photo=>URL.revokeObjectURL(photo.preview)),[]);
  const choose=(files:FileList|null)=>{if(!files)return;const next=[...files].filter(file=>file.type.startsWith("image/")).slice(0,12).map(file=>({id:crypto.randomUUID(),file,preview:URL.createObjectURL(file),rotation:0 as const,crop:0,perspective:0}));setPhotos(current=>[...current,...next].slice(0,12));};
  const update=(id:string,change:Partial<Photo>)=>setPhotos(current=>current.map(photo=>photo.id===id?{...photo,...change}:photo));
  const process=async()=>{setBusy(true);onError("");try{let dashboard:Dashboard|undefined;for(const photo of photos){const bytes=await preparePhoto(photo);dashboard=await importDocumentBytes(`corrected-${photo.file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}.png`,bytes);}if(dashboard)onImported(dashboard,photos.length);photos.forEach(photo=>URL.revokeObjectURL(photo.preview));setPhotos([]);}catch(error){onError(String(error));}finally{setBusy(false)}};
  return <section className="photo-editor" aria-labelledby="photo-editor-title"><div className="section-head"><div><h3 id="photo-editor-title">Prepare phone photos</h3><p>Correct each page before local OCR. The original photo is not uploaded.</p></div><label className="outline photo-picker"><ImagePlus/>Choose photos<input type="file" accept="image/*" multiple disabled={disabled||busy} onChange={event=>choose(event.target.files)}/></label></div>{photos.length>0&&<><div className="photo-list">{photos.map(photo=><article key={photo.id}><img src={photo.preview} alt="Schedule page preview" style={{transform:`rotate(${photo.rotation}deg)`}}/><div><strong>{photo.file.name}</strong><div className="photo-actions"><button className="outline" type="button" onClick={()=>update(photo.id,{rotation:((photo.rotation+270)%360) as Photo["rotation"]})} aria-label={`Rotate ${photo.file.name} left`}><RotateCcw/></button><button className="outline" type="button" onClick={()=>update(photo.id,{rotation:((photo.rotation+90)%360) as Photo["rotation"]})} aria-label={`Rotate ${photo.file.name} right`}><RotateCw/></button></div><label><Crop/>Crop edges <input type="range" min="0" max="20" value={photo.crop} onChange={event=>update(photo.id,{crop:Number(event.target.value)})}/><span>{photo.crop}%</span></label><label><WandSparkles/>Perspective <input type="range" min="-25" max="25" value={photo.perspective} onChange={event=>update(photo.id,{perspective:Number(event.target.value)})}/><span>{photo.perspective}</span></label></div><button className="icon-button" aria-label={`Remove ${photo.file.name}`} onClick={()=>{URL.revokeObjectURL(photo.preview);setPhotos(current=>current.filter(item=>item.id!==photo.id))}}>×</button></article>)}</div><button className="solid" disabled={busy||disabled} onClick={process}>{busy?"Correcting and reading…":`Correct and import ${photos.length} photo${photos.length===1?"":"s"}`}</button></>}</section>;
}

async function preparePhoto(photo:Photo):Promise<Uint8Array>{
  const bitmap=await createImageBitmap(photo.file);const quarter=photo.rotation===90||photo.rotation===270;const rotated=document.createElement("canvas");rotated.width=quarter?bitmap.height:bitmap.width;rotated.height=quarter?bitmap.width:bitmap.height;const context=rotated.getContext("2d",{alpha:false});if(!context)throw new Error("Photo correction is unavailable");context.fillStyle="#fff";context.fillRect(0,0,rotated.width,rotated.height);context.translate(rotated.width/2,rotated.height/2);context.rotate(photo.rotation*Math.PI/180);context.drawImage(bitmap,-bitmap.width/2,-bitmap.height/2);bitmap.close();
  const inset=Math.round(Math.min(rotated.width,rotated.height)*photo.crop/100);const width=Math.max(100,rotated.width-inset*2);const height=Math.max(100,rotated.height-inset*2);const output=document.createElement("canvas");output.width=width;output.height=height;const out=output.getContext("2d",{alpha:false});if(!out)throw new Error("Photo correction is unavailable");out.fillStyle="#fff";out.fillRect(0,0,width,height);
  if(photo.perspective===0)out.drawImage(rotated,inset,inset,width,height,0,0,width,height);else{const slices=Math.min(600,height);for(let row=0;row<slices;row++){const y=Math.floor(row*height/slices);const nextY=Math.ceil((row+1)*height/slices);const progress=(y/height-.5)*2;const scale=1-(photo.perspective/100)*progress;const targetWidth=width*scale;out.drawImage(rotated,inset,inset+y,width,nextY-y,(width-targetWidth)/2,y,targetWidth,nextY-y+1);}}
  const blob=await new Promise<Blob>((resolve,reject)=>output.toBlob(value=>value?resolve(value):reject(new Error("Corrected photo could not be encoded")),"image/png"));return new Uint8Array(await blob.arrayBuffer());
}
