import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { parseDays, to24Hour } from "../catalog/asu-class-search.mjs";

/**
 * The cross-language pin for weekday and clock parsing.
 *
 * `parseDays` and `to24Hour` in `scripts/catalog/asu-class-search.mjs` are
 * JavaScript; the schedule reader that has to agree with them is Rust. They
 * cannot be shared, so this table is what stops one being fixed without the
 * other — the same arrangement the mutation signing message uses.
 *
 * Keep in lockstep with GOLDEN_WEEKDAY_VECTOR and GOLDEN_CLOCK_VECTOR in
 * apps/desktop/src-tauri/src/schedule_reader.rs.
 */
const GOLDEN_WEEKDAY_VECTOR = [
  ["M", [1]],
  ["MWF", [1, 3, 5]],
  ["TTh", [2, 4]],
  ["TuTh", [2, 4]],
  ["Th", [4]],
  ["SuSa", [0, 6]],
  ["MTWThF", [1, 2, 3, 4, 5]],
  ["F", [5]],
  ["W", [3]],
];

const GOLDEN_CLOCK_VECTOR = [
  ["9:00 AM", "09:00"],
  ["12:00 PM", "12:00"],
  ["12:30 AM", "00:30"],
  ["1:15 PM", "13:15"],
  ["11:59 PM", "23:59"],
];

test("weekday parsing matches the published golden vector", () => {
  for (const [input, expected] of GOLDEN_WEEKDAY_VECTOR) {
    assert.deepEqual([...parseDays(input)].sort((a, b) => a - b), expected, `parsing ${input}`);
  }
  // The digraph rule: Thursday must not read as Tuesday followed by a stray h.
  assert.deepEqual(parseDays("Th"), [4]);
});

test("clock parsing matches the published golden vector", () => {
  for (const [input, expected] of GOLDEN_CLOCK_VECTOR) {
    assert.equal(to24Hour(input), expected, `parsing ${input}`);
  }
});

/**
 * The fixtures the Rust reader is tested against.
 *
 * These are real Tesseract output over real rendered screenshots — the images
 * sit beside the TSVs — regenerated by
 * scripts/fixtures/render-schedule-images.py. The previous generation was a
 * synthesized token stream, and it passed every test while the reader could not
 * read a single genuine week grid.
 */
const FIXTURES = [
  "week-grid",
  "week-grid-3x",
  "week-grid-gutter-only",
  "week-grid-dark",
  "google-week",
  "class-list",
  "unreadable-capture",
];
const READABLE = ["week-grid", "week-grid-3x", "google-week", "class-list"];

const fixturePath = (name, extension) =>
  new URL(
    `../../apps/desktop/src-tauri/test-fixtures/schedule/${name}.${extension}`,
    import.meta.url,
  );

test("every schedule fixture is a well-formed token stream with expectations beside it", () => {
  for (const name of FIXTURES) {
    const tsv = readFileSync(fixturePath(name, "tsv"), "utf8");
    const lines = tsv.trim().split("\n");
    assert.equal(lines[0].split("\t").length, 12, `${name} header`);
    for (const line of lines.slice(1)) {
      const columns = line.split("\t");
      assert.equal(columns.length, 12, `${name} row width`);
      // Geometry is the entire reason these fixtures exist.
      for (const index of [6, 7, 8, 9]) {
        assert.match(columns[index], /^\d+$/, `${name} column ${index} must be a pixel value`);
      }
      assert.ok(Number(columns[8]) > 0 && Number(columns[9]) > 0, `${name} zero-sized box`);
    }
    JSON.parse(readFileSync(fixturePath(name, "expected.json"), "utf8"));
  }
});

// Each fixture keeps the image it was read from, so a regeneration is
// reproducible and anyone can see what the reader was actually looking at.
test("every fixture keeps the screenshot it was read from", () => {
  for (const name of FIXTURES) {
    const png = readFileSync(fixturePath(name, "png"));
    assert.deepEqual(
      [...png.subarray(0, 8)],
      [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a],
      `${name}.png is not a PNG`,
    );
  }
});

test("the fixtures that must decline expect nothing", () => {
  for (const name of ["week-grid-gutter-only", "week-grid-dark", "unreadable-capture"]) {
    const expected = JSON.parse(readFileSync(fixturePath(name, "expected.json"), "utf8"));
    assert.deepEqual(expected, [], `${name} must expect no candidates`);
  }
});

test("every readable fixture describes the same three classes", () => {
  const expectations = READABLE.map((name) =>
    JSON.parse(readFileSync(fixturePath(name, "expected.json"), "utf8")),
  );
  for (const expected of expectations) {
    assert.deepEqual(
      expected.map((meeting) => meeting.title).sort(),
      ["CSE 240", "MAT 142", "PSY 101"],
      "a difference in output should mean a difference in layout handling, not in content",
    );
    for (const meeting of expected) {
      assert.equal(meeting.kind, "class_meeting");
      assert.match(meeting.startsAtLocal, /^([01]\d|2[0-3]):[0-5]\d$/);
      assert.ok(meeting.startsAtLocal < meeting.endsAtLocal);
      assert.ok(meeting.weekdays.length > 0);
      assert.ok(meeting.weekdays.every((day) => day >= 0 && day <= 6));
    }
  }
});
