import { useEffect, useMemo, useState } from "react";
import { listAiProviders, planScholarshipDeadline, prepareFundingSearch, requestFundingSearch, saveScholarshipOpportunity, type AiProviderStatus, type FundingSearchScope, type ScholarshipWorkspace } from "../../native";
import type { ScholarshipRunAction } from "./scholarshipTypes";
import { IdentityEvidence } from "./IdentityEvidence";
import { aiRecovery } from "../semester/SemesterScheduleAnalysisView";
export function FundingSearchAssistant({workspace,busy,run,onWrite}:{workspace:ScholarshipWorkspace;busy:boolean;run:ScholarshipRunAction;onWrite:(id:string)=>void}){
 const [goals,setGoals]=useState(""),[terms,setTerms]=useState(""),[selected,setSelected]=useState<string[]>([]),[scope,setScope]=useState<FundingSearchScope|null>(null),[consent,setConsent]=useState(false),[provider,setProvider]=useState<AiProviderStatus|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{void listAiProviders().then(p=>setProvider(p.find(x=>x.connected&&x.healthy)??null)).catch(()=>setError("Provider status unavailable. Local search still works."));},[]);
 useEffect(()=>{setScope(null);setConsent(false);},[goals,JSON.stringify(selected),JSON.stringify(workspace.opportunities),provider?.provider,provider?.model]);
 const keywords=terms.toLowerCase().split(/[,\n]/).map(t=>t.trim()).filter(Boolean);
 const found=useMemo(()=>workspace.opportunities.filter(o=>!keywords.length||keywords.some(t=>[o.title,o.summary??"",...o.fieldsOfStudy].join(" ").toLowerCase().includes(t))),[workspace.opportunities,terms]);
 const chosen=workspace.opportunities.filter(o=>selected.includes(o.id));
 const work=async(action:()=>Promise<void>)=>{setLoading(true);setError("");try{await action();}catch(e){setError(`${aiRecovery(e)} Local search and your terms are kept.`);}finally{setLoading(false);}};
 return <section className="scholarship-panel funding-search"><h2>Search assistant</h2><p>Turn your goals into search terms, then compare the evidence. Searches use opportunities already in your local catalog.</p>
 <label className="field">What are you looking for?<textarea maxLength={2000} value={goals} onChange={e=>setGoals(e.target.value)} placeholder="Research funding for a summer engineering project"/></label>
 <button className="outline" disabled={!goals.trim()} onClick={()=>setTerms([...new Set(goals.match(/[\p{L}\p{N}]{3,}/gu)??[])].join(", "))}>Build editable terms locally</button>
 <label className="field">Search terms, comma separated<input value={terms} onChange={e=>setTerms(e.target.value)}/></label>
 <p>{found.length} opportunities · Select up to four to compare. Refresh sources in Discover when you choose.</p>
 {error&&<p role="alert">{error}</p>}
 <div className="opportunity-list">{found.map(o=><article key={o.id}><label className="confirm-row"><input type="checkbox" checked={selected.includes(o.id)} disabled={!selected.includes(o.id)&&selected.length>=4} onChange={e=>setSelected(current=>e.target.checked?[...current,o.id]:current.filter(id=>id!==o.id))}/><strong>{o.title}</strong></label><p>{o.summary||"Read the published requirements before deciding fit."}</p><a href={o.canonicalUrl} target="_blank" rel="noreferrer">View source</a><small> · Refreshed {new Date(o.fetchedAt).toLocaleDateString()} · {o.freshness}</small><div className="record-actions"><button className="text-button" disabled={busy||o.state!=="discovered"} onClick={()=>void run(()=>saveScholarshipOpportunity({...o,state:"saved"}),"Opportunity saved locally.")}>{o.state==="discovered"?"Save opportunity":"Already saved"}</button><button className="text-button" onClick={()=>onWrite(o.id)}>Prepare editable writing draft</button>{o.deadline&&<button className="text-button" disabled={busy||!!o.taskIds.length} onClick={()=>void run(()=>planScholarshipDeadline(o.id),"Deadline task created by your request.")}>Create deadline task</button>}</div></article>)}</div>
 {chosen.length>0&&<div><h3>Compare selected opportunities</h3><div className="funding-comparison">{chosen.map(o=>{const fit=workspace.matches.find(m=>m.opportunityId===o.id);return <section key={o.id}><h4>{o.title}</h4><p>Award: {o.awardMinimum??"Not stated"}{o.awardMaximum?`–${o.awardMaximum}`:""} {o.currency??""} · Deadline: {o.deadline??o.deadlineLabel??"Needs verification"}</p><p>Required documents: {o.requiredDocuments.join(", ")||"Check source"}</p>{fit&&<><p>Matches: {fit.matched.map(m=>`${m.attribute}: ${m.requirement}`).join("; ")||"None confirmed"}</p><p>Needs review: {[...fit.unknown,...fit.ineligible].join("; ")}</p></>}<IdentityEvidence opportunity={o} profile={workspace.profile}/><a href={o.canonicalUrl} target="_blank" rel="noreferrer">Verify source requirements</a><p>{o.summary}</p></section>})}</div></div>}
 <details className="progressive-form"><summary>Optional AI help with search terms</summary><p>Only the goals you enter here and selected public opportunity excerpts are sent. Saved profile and identity details are excluded. Keep sensitive details out of this goals field.</p>
 {!provider?<p>Connect a provider in AI settings to use this optional action.</p>:<><p>{provider.provider} · {provider.model}</p><button className="outline" disabled={loading||!goals.trim()} onClick={()=>void work(async()=>{setScope(await prepareFundingSearch(goals,selected));setConsent(false);})}>Review exact data to send</button>{scope&&<><pre className="source-text">{JSON.stringify(scope,null,2)}</pre><label className="confirm-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I approve sending this displayed data for search-term suggestions.</label><button className="outline" disabled={loading||!consent} onClick={()=>void work(async()=>{try{const result=await requestFundingSearch({goals,opportunityIds:selected,sourceScope:JSON.stringify(scope),expectedProvider:provider.provider,expectedModel:provider.model,consent});setTerms(result.terms.join(", "));}finally{setConsent(false);}})}>{loading?"Getting suggestions…":"Suggest editable search terms"}</button></>}</>}
 </details></section>;
}
