import { useEffect, useState } from "react";
import { saveScholarshipOpportunity, type FundingCriterion, type ScholarshipOpportunity } from "../../native";
import type { ScholarshipRunAction } from "./scholarshipTypes";
export function FundingCriteriaEditor({opportunity,run,busy}:{opportunity:ScholarshipOpportunity;run:ScholarshipRunAction;busy:boolean}){
 const [quote,setQuote]=useState(""),[values,setValues]=useState(""),[url,setUrl]=useState(opportunity.canonicalUrl),[attribute,setAttribute]=useState<FundingCriterion["attribute"]>("culturalBackground"),[ambiguous,setAmbiguous]=useState(true);
 useEffect(()=>{setQuote("");setValues("");setUrl(opportunity.canonicalUrl);setAmbiguous(true);},[opportunity.id]);
 const list=values.split(",").map(v=>v.trim()).filter(Boolean);
 return <details className="progressive-form"><summary>Record explicit eligibility source text</summary><p>Copy the published criterion verbatim. Only literal, unambiguous values can produce a local identity match.</p><label className="field">Criterion type<select value={attribute} onChange={e=>setAttribute(e.target.value as FundingCriterion["attribute"])}><option value="culturalBackground">Ethnicity / cultural background</option><option value="religion">Religion</option><option value="affiliations">Community / organization</option></select></label><label className="field">Source quote<textarea maxLength={2000} value={quote} onChange={e=>setQuote(e.target.value)}/></label><label className="field">Explicit values in the quote, comma separated<input value={values} onChange={e=>setValues(e.target.value)}/></label><label className="field">Source URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label><label className="confirm-row"><input type="checkbox" checked={ambiguous} onChange={e=>setAmbiguous(e.target.checked)}/>Wording needs student review</label>
 <button className="outline" disabled={busy||!quote.trim()||!/^https:\/\//.test(url)||!ambiguous&&(!list.length||list.some(v=>!quote.toLowerCase().includes(v.toLowerCase())))} onClick={()=>void run(()=>saveScholarshipOpportunity({...opportunity,eligibilityCriteria:[...(opportunity.eligibilityCriteria??[]),{attribute,values:list,sourceQuote:quote,sourceUrl:url,capturedAt:new Date().toISOString(),ambiguous}]}),"Eligibility source saved locally.")}>Save reviewed criterion</button>
 {(opportunity.eligibilityCriteria??[]).map((c,i)=><p key={i}>{c.sourceQuote} <button className="text-button" disabled={busy} onClick={()=>void run(()=>saveScholarshipOpportunity({...opportunity,eligibilityCriteria:opportunity.eligibilityCriteria?.filter((_,index)=>index!==i)}),"Criterion removed.")}>Remove criterion</button></p>)}</details>;
}
